weeder_controller:
  ros__parameters:
    link1_length: 0.190
    link2_length: 0.250
    trajectory_time_ms: 250  # time in milliseconds to execute the trajectory
    tf_callback_period: 100  # milliseconds between each tf callback
    image_buffer_size: 3 # averaging target position of these many images
    frames_delay: 6 # checks the above amount of images and then idle for these many
    # camera_rgb_topic: /simulated_D435/image_rect
    # camera_depth_topic: /simulated_D435/depth_image
    # camera_info_topic: /simulated_D435/camera_info
    camera_rgb_topic: /weeder_robot/real_D455/color/image_raw
    camera_depth_topic: /weeder_robot/real_D455/aligned_depth_to_color/image_raw
    camera_info_topic: /weeder_robot/real_D455/color/camera_info
    roi_size: 20
    morph_kernel_size: 5
    depth_roi_size: 40
    mask_type: ExGR # options: HSV_red, ExG_threshold, ExG_Otsu, ExGR. Default: HSV_red

    visual_servoing:
      filtering: false
      alpha: [1.0, 1.0, 0.4] # for target_camera_position (1.0 = no filtering), THIS VALUE IS NOT USED RIGHT NOW
      beta: [0.6, 0.6, 0.6] # for error [dx, dy, dz] (1.0 = no filtering)
      lambda_IBVS: [3.0, 3.0, 1.5] # controller gain (it's not a filter option, it's always active)
      lambda_PBVS: [0.8, 0.8, 0.4] # controller gain (it's not a filter option, it's always active)
      controller_period_ms: 50 # (called dt in the node) remeber 0.0 < lambda*dt < 2.0 for stbility
      smoothing: 1.2 # 1.0 - 1.5 = trajectories are slower than control, if < 1.0 faster trajectories, possibile jerk
      control_threshold: 0.1 # stop condition for visual servoing
      desired_feature: [0.0, 0.0, 0.8] # u, v, Z: first two are in percentage of screen, last one in meters. [0, 0, Z] means center of the image

weeder_controller_with_YOLO:
  ros__parameters:
    link1_length: 0.190
    link2_length: 0.250
    trajectory_time_ms: 250  # time in milliseconds to execute the trajectory
    tf_callback_period: 100  # milliseconds between each tf callback
    image_buffer_size: 3 # averaging target position of these many images
    frames_delay: 6 # checks the above amount of images and then idle for these many
    camera_rgb_topic: /simulated_D435/image_rect
    camera_depth_topic: /simulated_D435/depth_image
    camera_info_topic: /simulated_D435/camera_info
    confidence_threshold: 0.5
    depth_roi_size: 24
    CUDA_device_id: 0

    visual_servoing:
      filtering: false
      alpha: [1.0, 1.0, 0.4] # for target_camera_position (1.0 = no filtering), THIS VALUE IS NOT USED RIGHT NOW
      beta: [0.6, 0.6, 0.6] # for error [dx, dy, dz] (1.0 = no filtering)
      lambda_IBVS: [5.0, 5.0, 1.5] # controller gain (it's not a filter option, it's always active)
      lambda_PBVS: [0.8, 0.8, 0.4] # controller gain (it's not a filter option, it's always active)
      controller_period_ms: 50 # (called dt in the node) remeber 0.0 < lambda*dt < 2.0 for stbility
      smoothing: 1.2 # 1.0 - 1.5 = trajectories are slower than control, if < 1.0 faster trajectories, possibile jerk
      control_threshold: 0.1 # stop condition for visual servoing
      desired_feature: [0.0, 0.05, 0.8] # u, v, Z: first two are in percentage of screen, last one in meters. [0, 0, Z] means center of the image

gazebo_target_visualizer:
  ros__parameters:
  # Colors are always RGBA
  # Uncomment only one of the following

    # # Red Target
    # material:
    #   ambient: [1.0, 0.0, 0.0, 1.0]       # colore del materiale senza luce
    #   diffuse: [1.0, 0.0, 0.0, 1.0]       # colore del materiale alla luce
    #   specular: [1.0, 0.5, 0.5, 1.0]      # riflettività (alto = plastica lucida)
    #   emissive: [0.5, 0.0, 0.0, 1.0]      # luminosità emessa

    # # Light Green Target 
    # material: 
    #   ambient: [0.2, 0.6, 0.2, 1.0]      
    #   diffuse: [0.3, 0.8, 0.3, 1.0]
    #   specular: [0.05, 0.05, 0.05, 1.0] 
    #   emissive: [0.0, 0.0, 0.0, 1.0] 

    # # Medium Green Target
    # material: 
    #   ambient: [0.10, 0.4, 0.10, 1.0]      
    #   diffuse: [0.15, 0.55, 0.15, 1.0]
    #   specular: [0.03, 0.03, 0.03, 1.0] 
    #   emissive: [0.0, 0.0, 0.0, 1.0] 
    
    # Dark Green target
    material: 
      ambient:  [0.05, 0.18, 0.05, 1.0]    
      diffuse:  [0.08, 0.30, 0.08, 1.0]
      specular: [0.01, 0.01, 0.01, 1.0] 
      emissive: [0.0, 0.0, 0.0, 1.0]
